### PR TITLE
Escape command substitutions in gromacs_activate.csh

### PR DESCRIPTION
**Pull request by martin-g**
Until now the command substitutions were evaluated eagerly, i.e. at build time.
Now they will be evaluated at run/execution time.

To confirm the problem in the current version of the script:
- download the latest Gromacs package from Anaconda, e.g. https://anaconda.org/conda-forge/gromacs/2023.4/download/linux-64/gromacs-2023.4-nompi_cuda_h6303bc7_3.conda
- unzip *.conda
- tar xvf pkg-gromacs-*.zst
- less etc/conda/activate.d/gromacs_activate.csh
- you will see the following at the top:
```
setenv uname x86_64
if ( x86_64 == "arm64" 
```

i.e. the environment variable `uname` is already set to `x86_64` because this is the CPU architecture at Azure CI.
This script is unusable at Mac OSX ARM64.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Review by mabraham — APPROVED** [review]
Good catch!

**Comment by xiki-tempula** [comment]
It seems that this PR has removed all the CUDA builds?

**Comment by mabraham** [comment]
Not by design! @martin-g thoughts?

**Comment by martin-g** [comment]
The re-rendering decided that those files are no more needed.
@xhochy Any hints why the renderer does this ?

**Comment by martin-g** [comment]
According to https://conda-forge.org/docs/maintainer/knowledge_base/#cuda-builds all that is needed is having `- {{ compiler('cuda') }}` in meta.yaml, and it is (still) there - https://github.com/conda-forge/gromacs-feedstock/blob/218742281fb62fe72e55c835e9204f5b73370a4d/recipe/meta.yaml#L33

**Comment by martin-g** [comment]
@jakirkham I believe you are the CUDA expert at Conda-Forge. Do you know why the re-rendering removed the CUDA support for gromacs ?
At https://github.com/conda-forge/gromacs-feedstock/pull/54 I am trying different things but I cannot make it bring back `nvcc` compiler in the generated settings.

**Comment by martin-g** [comment]
@conda-forge/core Could someone help us here with a CUDA compiler settings change after re-rendering ? Thanks!

**Pull request merged**
