### PR TITLE
Add dedicated build string for MPI cuda build

### PR DESCRIPTION
**Pull request by xiki-tempula**
The MPI cuda build doesn't have dedicated build string for it so it used to roll with `gromacs=2023.4=hfe2713a_3` this PR shall change it to `gromacs-2024.2-mpi_openmpi_cuda_hee10d94_2`

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please rerender

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please rerender

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please rerender

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please rerender

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please rerender

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please rerender

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please rerender

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please rerender

**Review by mabraham — APPROVED** [review]

**Pull request merged**
