### PR TITLE
Try to bring back CUDA builds

### PR DESCRIPTION
**Pull request by martin-g**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by carterbox** [comment]
```
  skip: true  # [win or cuda_compiler_version not in ("11.2", "None")]
```
You need to change this line and rerender. We don't support CUDA 11.2 anymore.

**Comment by martin-g** [comment]
Thank you for the hint, @carterbox !
I will work on this later today!

**Comment by mabraham** [comment]
> Thank you for the hint, @carterbox ! I will work on this later today!

I think a PR from earlier today just did this already

**Comment by martin-g** [comment]
> I think a PR from earlier today just did this already

Awesome!
Seems to be already fixed with https://github.com/conda-forge/gromacs-feedstock/pull/52

**Pull request closed without merging**
