### PR TITLE
Enable the CUDA-MPI build

### PR DESCRIPTION
**Pull request by xiki-tempula**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

https://github.com/conda-forge/gromacs-feedstock/issues/35

### CODE REVIEW

**Comment by xiki-tempula** [comment]
Thanks for the comment.

**Comment by xiki-tempula** [comment]
> This would work as you intend only if the openmpi package has suitable cuda awareness already built in. Does it?

I do agree that this will give the best performance but there is value for a MPI cuda version where one could do replex with cuda.

**Comment by xiki-tempula** [comment]
@mabraham It seems that the build runs fine?

**Comment by xiki-tempula** [comment]
I built this package locally and it seems to be working perfectly fine.

**Comment by mabraham** [comment]
I assume there is no need to bump the build number as this MR is just adding a new build

**Pull request merged**
