### PR TITLE
Create CUDA package for linux

### PR DESCRIPTION
**Pull request by douglowe**
CUDA support should be for single-precision,
nompi, builds only.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by douglowe** [comment]
@conda-forge-admin, please rerender

**Comment by douglowe** [comment]
This replaces PR https://github.com/conda-forge/gromacs-feedstock/pull/3. Compared with that PR, I've squashed the commit history so it's a bit cleaner, updated GROMACS to 2022.1, and modified the logic for the inclusion of the `ocl-icd` package in `host` and `run`, so that OpenCL support is only added on linux when CUDA support is not included.

**Comment by douglowe** [comment]
It looks like the additive logic is stopping the building of gromacs for CUDA with double precision, or MPI support, even though build scripts for these are created. So perhaps (once everything is built) we'll release these packages without waiting for the additive logic for create the build scripts is fixed.

**Comment by douglowe** [comment]
@conda-forge-admin, please rerender

**Comment by douglowe** [comment]
@jan-janssen - I've looked at the selector bug more, and it seems that it's an issue for the creation of build recipes, but then within the build recipes themselves additive logic is used, so we shouldn't release more packages than we intend (just waste a few conda-forge build resources).

If you're happy with the package changes I've made I'll merge this PR.

**Review by jan-janssen — APPROVED** [review]
> If you're happy with the package changes I've made I'll merge this PR.

Looks good to me

**Pull request merged**
