### PR TITLE
disable mpi build for osx arm64

### PR DESCRIPTION
**Pull request by xiki-tempula**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please rerender

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please rerender

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please rerender

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please restart ci

**Review by mabraham — APPROVED** [review]

**Comment by douglowe** [comment]
I don't think that changing the readme will make the changes that you want.

You need to add some more if statements to the build recipe. I'll look at these and see if I can make something sensible.

**Comment by xiki-tempula** [comment]
@douglowe Sorry for the confusion. I add the whole changes but I cannot get the pipeline to run. So I strip back to only include the readme.

**Comment by xiki-tempula** [comment]
@douglowe This PR shall now contain all the relevant files, but I cannot get the pipeline to work though.

**Comment by douglowe** [comment]
I think you should get your solution to work if you use `osx_arm64`, rather than `osx and arm64`. Try that, and request a rerender.

The one issue there might be is that rerendering can often mangle the select statements just above this selection. So after rerendering do check to make sure that they look the same as before.

**Comment by douglowe** [comment]
Ahh! I'd assumed that they would use `osx_arm64`, not just `arm64` to indicate OSX on arm64 architecture.

So, ignore my first suggestion. Instead can you try deleting `and osx` (as this is redundant information), and only use `mpi == 'openmpi' and arm64`. It might have been that the logic engine was getting confused by two (possibly conflicting) OS select statements.

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please rerender

**Comment by xiki-tempula** [comment]
@douglowe I guess it didn't make much difference. I wonder if you mind merge this PR? This PR shall be merged into Mark's PR so not to the main yet. I guess we can check if the pipeline works in Mark's PR.

**Comment by douglowe** [comment]
That is strange. But yes, I agree that we should merge this into the other PR, and continue trying to debug it there.

**Pull request merged**
